### PR TITLE
Simple way to download maven artifact and use them for spark master and workers

### PR DESCRIPTION
**Pull request by jkremser**
### Description
before it runs the actual master/worker, it runs dummy/noop `spark-submit` command with `--packages` argument so that it can download the jars into `/tmp`. These are then reused when starting the nodes.

#### Related Issue
#213 

#### Types of changes

 :sparkles: New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by jkremser** [comment]
so far so good..

```
cat <<EOF | kubectl apply -f -
apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
  name: my-spark-cluster
spec:
  worker:
    instances: "2"
  master:
    instances: "1"
  mavenDependencies:
    - com.amazonaws:aws-java-sdk-pom:1.10.34
    - org.apache.hadoop:hadoop-aws:2.7.3
EOF
```

```
λ oc get pods
NAME                              READY     STATUS      RESTARTS   AGE
my-spark-cluster-m-x689t          1/1       Running     0          11m
my-spark-cluster-w-sb6t5          1/1       Running     0          11m
my-spark-cluster-w-t5wmn          1/1       Running     0          11m
spark-operator-2814583976-x9tb4   1/1       Running     0          11m

```

```
λ oc exec my-spark-cluster-m-x689t -- ls /tmp/jars | grep aws
com.amazonaws_aws-java-sdk-1.7.4.jar
org.apache.hadoop_hadoop-aws-2.7.3.jar
```

```
λ oc exec my-spark-cluster-w-sb6t5 -- ls /tmp/jars | grep aws
com.amazonaws_aws-java-sdk-1.7.4.jar
org.apache.hadoop_hadoop-aws-2.7.3.jar
```

**Comment by jkremser** [comment]
@elmiko could you ptal?

**Comment by elmiko** [comment]
@jkremser definitely, i may not get to it this afternoon, but i will try to test it before the end of the week.

**Comment by elmiko** [comment]
ok, i have run some preliminary tests and i _think_ things are working as intended but i am having difficulty testing it accurately.

here is what i tried,

1. install new spark-operator
2. spawn a cluster with a maven dependency
3. hook up an app to the cluster

(part 3 did not work for me, but because of other issues.)

i used this definition for the cluster
```
{
    "apiVersion": "radanalytics.io/v1",
    "kind": "SparkCluster",
    "metadata": {
        "name": "mvn-test"
    },
    "spec": {
        "master": {
            "instances": 1
        },
        "worker": {
            "instances": 1
        },
        "customImage": "docker.io/radanalyticsio/openshift-spark:2.3-latest",
        "mavenDependencies": [
            "org.apache.spark:spark-sql-kafka-0-10_2.11:2.3.0"
        ]
    }
}
```

i see that it downloaded the jar i requested, but i also see some errors in the logs around failed logins. i'm not sure what is causing that.

i am attaching the logs for the master and worker.
[master.log.txt](https://github.com/radanalyticsio/spark-operator/files/3258682/master.log.txt)
[worker.log.txt](https://github.com/radanalyticsio/spark-operator/files/3258684/worker.log.txt)

i would have liked to test against an app, but there are other problems with my blending an oshinko-s2i app that are causing me grief.

on the whole, it looks ok, but i am curious about the errors in the logs.

**Comment by jkremser** [comment]
thanks Mike. failed logins are usually related to the missing uid in `/etc/passwd`. So I guess the `/entrypoint` script wasn't run. I will look into 2.3 image to check what's different here

**Comment by jkremser** [comment]
I fixed that for Spark 2.4 images, however in Spark 2.3 and lower, the `spark-submit`'s logging behaves slightly differently so it's not possible to hide the error completely. It's caused by the fact we are "spark-submitting" a non existent class just for the sake of downloading the jars.. if there is some other very cheap operation that could be done instead, I'd do that, but I haven't found any. Submitting spark-pi for instance doesn't throw any errors, but it runs longer.

In the last commit I've also added support for external maven repos, so it's now possible to add a library that's not in maven central. For instance @willb's silex can be added by:

```
cat <<EOF | kubectl apply -f -
apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
  name: my-spark-cluster
spec:
  worker:
    instances: "2"
  master:
    instances: "1"
  mavenRepositories:
     - https://dl.bintray.com/willb/maven/
  mavenDependencies:
    - com.redhat.et:silex_2.11:0.1.2
EOF
```

**Comment by elmiko** [comment]
i will give it another try, i thought i saw some weird errors coming out of the 2.4 image as well.

**Comment by elmiko** [comment]
lgtm, i tested this with a similar setup as previously.

i also tested with our new 2.4.0 images from radanalytics and everything looks good.

**Pull request merged**
