### PR TITLE
[WIP] Extract rc spec type

### PR DESCRIPTION
**Pull request by sharebear**
Initial PR to discuss API changes as described in #79, does this look like what you were thinking.

## Description
See individual commit comments for more detail but in short the following config

```
    workerNodes: "2"
    masterNodes: "1"
    memory: "1Gi"
    cpu: 0.2
```

Is now expressed with the following

```
    worker:
      replicas: "2"
      limits:
        memory: "1Gi"
        cpu: 0.2
    master:
      replicas: "1"
      limits:
        memory: "1Gi"
        cpu: 0.2
```

## Related Issue

#79 

## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case / Automation (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
This looks ok, thanks for the PR.

currently the CI fails on some NPE

https://travis-ci.org/radanalyticsio/spark-operator/jobs/436765832#L2764
```
2018-10-03 18:08:50 WARN  WatchConnectionManager:201 - Exec Failure
java.lang.NullPointerException
	at io.radanalytics.operator.cluster.SparkClusterOperator.onModify(SparkClusterOperator.java:41)
	at io.radanalytics.operator.cluster.SparkClusterOperator.onModify(SparkClusterOperator.java:12)
	at io.radanalytics.operator.common.AbstractOperator.handleAction(AbstractOperator.java:385)
```

Btw. if you you are interested in writing operators in Java or other JVM languages for your stuff, check out https://github.com/jvm-operators. Thre are also some examples and maven archetypes.

**Comment by sharebear** [comment]
I'm aware of the build error, that's due to this line ;) https://github.com/radanalyticsio/spark-operator/pull/103/files#diff-bd3033ebf395a0180a6543ca89fc3276R137

I wanted to make sure you were ok with the difference in behaviour of defaulting with this change. i.e. the defaults in the json schema will have to be copied in the code for the case where the whole master/worker object is not configured at all in the configmap. Is this ok? Slightly more verbose description of this issue is in the commit comment on https://github.com/radanalyticsio/spark-operator/pull/103/commits/e5a84cd006e0f82a990c45bcea17863328d5d4ee

I can probably fix the test configmaps and nullsafing/defaulting in the code tonight.

**Comment by Jiri-Kremser** [comment]
> I wanted to make sure you were ok with the difference in behaviour of defaulting with this change. i.e. the defaults in the json schema will have to be copied in the code for the case where the whole master/worker object is not configured at all in the configmap. Is this ok?

Hmm, and isn't it possible to somehow get the default value from the generated classes? Let me check.

**Comment by Jiri-Kremser** [comment]
>The existing code base sets the same values for both the resource request
and resource limit. Was this intentional behaviour?

Yes, this is intentional.

**Comment by Jiri-Kremser** [comment]
@sharebear it's not good idea to copy the default values from the json schema to code. You can check if the master/worker object is there and if not, you can create a new instance... this would also reduce the null checks in the code. Something like:

```java
    private SparkCluster fillDefaults(SparkCluster cluster) {
        if (cluster.getMaster() == null) {
            cluster.setMaster(new Master());
        }
        if (cluster.getMaster().getLimits() == null) {
            cluster.getMaster().setLimits(new Limits());
        }
        return cluster;
    }
```

**Comment by sharebear** [comment]
The only failure on this build should be fixed by merging the following PR https://github.com/radanalyticsio/spark-operator/pull/107 and then triggering a new build.

**Comment by sharebear** [comment]
Before I remove the WIP tag on this I just wanted to bring up a small problem I've not fixed yet.

jsonschema2pojo has created a type called `Master` which is used as the type of both the `master` and `worker` properties on `SparkCluster`. This is kind of confusing. From my experience with swagger and the generation tools there I would have expected the type that was created to be called `RCSpec`, is this behaviour configurable?

**Comment by sharebear** [comment]
With the code as it is both `getMaster()` and `getWorker()` return the type `Master`, ideally I would like both of these methods to return at type called `RCSpec` (open for better names). I dug into the jsonschema2pojo code and it looks like in the next version (currently at 1.0.0-beta1) I can set a `title` field on the defintion, which together with the `useTitleAsClassname` configuration gives me the behaviour I'm looking for. This change would require some refactoring to the `env` and `sparkConfiguration` definitions. Would you be open to a PR bumping the jsonschema2pojo-maven-plugin to 1.0.0-beta1 with the necessary  refactorings mentioned above?

As an alternative workaround I think I can force jsonschema2pojo to create separate Master and Worker types again, with the caveat of being harder to establish code reuse.

**Comment by Jiri-Kremser** [comment]
> Would you be open to a PR bumping the jsonschema2pojo-maven-plugin to 1.0.0-beta1 with the necessary refactorings mentioned above?

Definitely! I hope there are not many breaking changes in `1.0.0`

**Comment by Jiri-Kremser** [comment]
lgtm, let's not complicate this PR with the `jsonschema2pojo-maven-plugin` upgrade. I like the use of 

```java
Optional.ofNullable()...orElse()/ifPresent()
```

Thanks!

**Pull request merged**
