### PR TITLE
Replaces infinte bash `until` loops with an equivalent check using tr…

### LINKED ISSUE #117: Potential infinite loop in start_minikube()
### Describe the problem:

When investigating the build problems with resource limits added I attempted to bump the minikube version to the latest (v0.30.0). The logic in start_minikube() entered an infinite loop causing the build to continue until it reached the max allowed build time in travis.

I believe the fix is two `until...done` loops with calls to `os::cmd::try_until_text`

#### Steps to reproduce:

  1. Update .travis.yml with MINIKUBE_VERSION=v0.30.0
  2. Trigger build
  
#### Observed Results:

  * Shell script entered infinite loop
  
#### Expected Results:

  * Loop should timeout if expected state is not reached within reasonable amount of time (5-15 mins, not 2 hours).

### PR DESCRIPTION
**Pull request by sharebear**
…y_until_text

## Description
See summary

Fixes #117

Note this does not necessarily fix any problems with upgrading minikube,
just ensures that any failures do not cause the build to take 2 hours
before failing.

## Related Issue
#117 

## Types of changes

- [x] Updated docs / Refactor code / Added a tests case / Automation (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
Hi, these changes make sense.

strange, it's failing on
```
[ERROR] PID 3833: test/lib/log/stacktrace.sh:0: `'none' driver does not support 'minikube docker-env' command` exited with status 127.
```

btw. kube-dns pod contains more containers, so when calling the `os::cmd::try_until_text "${BIN} -n kube-system get pod -lk8s-app=kube-dns -o yaml" 'ready: true'` it passes even though not all the containers are ready.

```bash
kubectl -n kube-system get pod -lk8s-app=kube-dns -o yaml | grep -i ready
      type: Ready
      ready: true
      ready: true
      ready: true
```

Perhaps something like 
```bash
os::cmd::try_until_text "kubectl -n kube-system get pod -lk8s-app=kube-dns -o yaml | grep 'ready: true' | wc -l" '3'
```

could be better

**Comment by sharebear** [comment]
> btw. kube-dns pod contains more containers, so [...] it passes even though not all the containers are ready.

I'm no jsonpath expert but I believe that bug was in the code I replaced too, so I didn't stress over trying to fix that in the same PR.

Not had a chance to check out the last build error, will probably be the weekend before I have time to dive into it.

**Comment by sharebear** [comment]
`minikube docker-env` also fails on master, the output is just hidden in the logs. When initialising the testlib `errexit` is set, which has now been moved to before the call to `minikube docker-env`.

The reason that fails for the `none` driver is that there is no alternative dockerd running inside a vm, minikube uses the hosts dockerd.. therefore I think we can safely just delete this line.

**Comment by Jiri-Kremser** [comment]
may I ask about your motivation to contribute to this project? Do you use spark-operator for anything real?

**Comment by sharebear** [comment]
> may I ask about your motivation to contribute to this project?

It was a combination of issues tagged with Hacktoberfest that looked like something that fit my skillset and seeing an opportunity to take a closer look at "operators" in general and the comparison to other tools for declarative configuration such as terraform.

I've previously been on a project that attempted something similar for scheduling Apache Flink jobs long before the "operator" term was a thing. Flink was replaced with something similar when I was on parental leave so that never saw the light of day :)

> Do you use spark-operator for anything real?

Nope, but I'm a Java consultant by day and from my previous experience see potential in Apache Beam for streaming workloads so it's useful to stay up-to-date on the related tech if I ever end up on a project with those kind of requirements again. Lots of people running OpenShift/k8s on premise here in Norway so it's not entirely unlikely.

**Comment by Jiri-Kremser** [comment]
Cool, I've just created channel on freenode IRC called `#spark-operator` so feel free to join.

**Pull request merged**
