### PR TITLE
Add resource limits to operator

### PR DESCRIPTION
**Pull request by sharebear**
Github wouldn't let me reopen https://github.com/radanalyticsio/spark-operator/pull/106 see my final comment there.

### CODE REVIEW

**Comment by sharebear** [comment]
```
    Last State:     Terminated
      Reason:       OOMKilled
```

**Comment by Jiri-Kremser** [comment]
If, I run the tests locally by:

```bash
git submodule update --init --recursive
BIN=oc CRD=0 .travis/.travis.test-oc-and-k8s.sh
```
they pass.
I will also try to open couple of PRs with different values and see what will be ok with travis. This is hard to debug.

**Comment by Jiri-Kremser** [comment]
* https://github.com/radanalyticsio/spark-operator/pull/111
* https://github.com/radanalyticsio/spark-operator/pull/112
* https://github.com/radanalyticsio/spark-operator/pull/113
* https://github.com/radanalyticsio/spark-operator/pull/114

:popcorn: :grin:

**Comment by Jiri-Kremser** [comment]
let's go with 400megs

> this doesn't explain why the tests worked locally though.

Travis runs the openshift at version 3.9 and I run 3.7 locally, when trying 3.9 it also failed for me.

**Comment by sharebear** [comment]
Is there some kind of race condition in the tests? Strange that here both CRD tests failed and in my other PR https://github.com/radanalyticsio/spark-operator/pull/109 one CRD test failed. I'm wondering if this is some kind of race condition where there is a delay between the CRD definition being applied and it actually being validatable as a resource type.

**Comment by Jiri-Kremser** [comment]
tests failed for CRD use-case because of 

```bash
error: unable to recognize "/home/travis/build/radanalyticsio/spark-operator/.travis/../examples/cluster-cr.yaml": no matches for radanalytics.io/, Kind=sparkcluster
```
--https://travis-ci.org/radanalyticsio/spark-operator/jobs/439294239#L2636

It has nothing to do with readiness/liveness probe. Actually, the operator should be able to handle also those events that happened before it was up and running. K8s api server somehow replays the events for it. I don't know how this is happening, but I can create CR/CM, then after some time start the operator and it will be notified about the event and deploys the cluster.

However, there might be an issue if the operator dies during deploying the cluster, then it end up in a broken state, where CM/CR exists in K8s, but the even wasn't handled properly. It will be restarted, but will do nothing about the event it already saw, but dies because of it. I've crated issue for it recently when playing with the limits - #115

**Comment by Jiri-Kremser** [comment]
I'm looking into it again and I think you might be right, it can be a race condition which happens if the resources are limited and the operator is slow. Hotfix can be checking if the string like "CustomResource watcher running for kinds sparkcluster" appeared in the log and only then create the cluster, but better thing to do would be the probe. Btw. from logs it [looks like](https://travis-ci.org/radanalyticsio/spark-operator/jobs/439294239#L2659) the start took 12 seconds, which is quite a lot. Perhaps the limits for CPU could be a little bit higher.

Nice catch!

**Comment by sharebear** [comment]
>  Hotfix can be checking if the string like "CustomResource watcher running for kinds sparkcluster" appeared in the log

I was thinking more along the lines of checking the output of `get crd`

```
os::cmd::try_until_text "${BIN} get crd" 'sparkcluster'
```
> Btw. from logs it looks like the start took 12 seconds, which is quite a lot. Perhaps the limits for CPU could be a little bit higher.

Agreed, will take a look if I find a free 30 mins tonight...

**Comment by Jiri-Kremser** [comment]
something like
`resources.limits.cpu: 1000m`
`resources.requests.cpu: 250m`
should do the trick

**Comment by sharebear** [comment]
Looks good now... both with just the test change to avoid the race condition and with the CPU limits changed.

**Pull request merged**
